
package com.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FisrtWebServiceImplementService", targetNamespace = "http://server.webservice.com/", wsdlLocation = "http://localhost:8099/getAddress?wsdl")
public class FisrtWebServiceImplementService
    extends Service
{

    private final static URL FISRTWEBSERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FISRTWEBSERVICEIMPLEMENTSERVICE_EXCEPTION;
    private final static QName FISRTWEBSERVICEIMPLEMENTSERVICE_QNAME = new QName("http://server.webservice.com/", "FisrtWebServiceImplementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8099/getAddress?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FISRTWEBSERVICEIMPLEMENTSERVICE_WSDL_LOCATION = url;
        FISRTWEBSERVICEIMPLEMENTSERVICE_EXCEPTION = e;
    }

    public FisrtWebServiceImplementService() {
        super(__getWsdlLocation(), FISRTWEBSERVICEIMPLEMENTSERVICE_QNAME);
    }

    public FisrtWebServiceImplementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FISRTWEBSERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public FisrtWebServiceImplementService(URL wsdlLocation) {
        super(wsdlLocation, FISRTWEBSERVICEIMPLEMENTSERVICE_QNAME);
    }

    public FisrtWebServiceImplementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FISRTWEBSERVICEIMPLEMENTSERVICE_QNAME, features);
    }

    public FisrtWebServiceImplementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FisrtWebServiceImplementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FisrtWebServiceImplement
     */
    @WebEndpoint(name = "FisrtWebServiceImplementPort")
    public FisrtWebServiceImplement getFisrtWebServiceImplementPort() {
        return super.getPort(new QName("http://server.webservice.com/", "FisrtWebServiceImplementPort"), FisrtWebServiceImplement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FisrtWebServiceImplement
     */
    @WebEndpoint(name = "FisrtWebServiceImplementPort")
    public FisrtWebServiceImplement getFisrtWebServiceImplementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.com/", "FisrtWebServiceImplementPort"), FisrtWebServiceImplement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FISRTWEBSERVICEIMPLEMENTSERVICE_EXCEPTION!= null) {
            throw FISRTWEBSERVICEIMPLEMENTSERVICE_EXCEPTION;
        }
        return FISRTWEBSERVICEIMPLEMENTSERVICE_WSDL_LOCATION;
    }

}
